config/routes.rb
TechClubWebsite::Application.routes.draw do

  get "front_page/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :comments
  
  resources :sessions 

  resources :profile_claims

  resources :profiles

  resources :users

  resources :posts

  resources :projects

  resources :profiles do
    resources :profile_claims, :path => "claim"
  end

  root :to => "front_page#index"

  match ":id" => "posts#show"

end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                  :integer          not null, primary key
#  first_name          :string(255)
#  last_name           :string(255)
#  active              :boolean
#  github_profile      :string(255)
#  major               :string(255)
#  skills              :text
#  github_access_token :string(255)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#

class Profile < ActiveRecord::Base
  has_one :user
  has_one :profile_claim
  
  has_many :teams, :foreign_key => "developer_id"
  has_many :projects, :class_name => "Project", :through => :teams
  has_many :leads, :class_name => "Projects"
  
  attr_accessible :active, :first_name, :github_access_token, :github_profile, :last_name, :major, :skills
  
  def full_name
    [self.first_name, self.last_name].join(' ')
  end

  def skill_tags
    skills.split(/[,;]/).each { |skill| skill.strip! }
  end  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.json
  def new
    @profile = Profile.new
    @projects = Project.all

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
    @projects = Project.all
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(params[:profile])
    @projects = Project.all

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render json: @profile, status: :created, location: @profile }
      else
        format.html { render action: "new" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.json
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for(@profile, :html => { :class => "form-horizontal"} ) do |f| %>
  <legend>Profiles</legend>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :first_name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :first_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :last_name, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :last_name %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :active, :class => "control-label" %>
    <div class="controls">
    <%= f.check_box :active %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :github_profile, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :github_profile %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :major, :class => "control-label" %>
    <div class="controls">
    <%= f.text_field :major %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :skills, :class => "control-label" %>
    <div class="controls">
      <div class="input-prepend">
        <span class="add-on"><i class="icon icon-tags"></i></span><%= f.text_field :skills, :placeholder => "c, c++, ruby, etc...", :class => "input-xxlarge" %>
      </div>
    </div>
  </div>
  <div class="control-group">
    <%= f.label "Active Projects", :class => "control-label" %>
    <div class="controls">
    <% if @projects.length > 0 %>
      <% @projects.each do |project| %>
         <%= label_tag :project_ids, :class => "checkbox" do %>
         <%= check_box_tag :project_ids, project.id, @profile.projects.include?(project), :name => "profile[project_ids][]" %>
         <%= project.title %>
         <% end %>
      <% end %>
    <% else %>
      <p style="padding-top: 5px;">
        <span class="label label-warning"><i class="icon-white icon-warning-sign"></i> No Projects</span> Create a <%= link_to "project", new_project_path %> now.
      </p>
    <% end %>
    </div>
  </div>
  <div class="form-actions">
    <% btn_submit_name = "Submit" %>
    <% btn_submit_name = "Save Changes" if @profile.id %>
    <%= f.submit btn_submit_name, :class => "btn btn-primary"%>
    <%= button_tag "Cancel", :class => "btn" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<div class="span12">
  <%= link_to 'New Profile', new_profile_path, :class => "btn btn-mini btn-primary pull-right" %>
  <h3>Members</h3>

  <table class="table">
    <tr>
      <th>Name</th>
      <th>Active</th>
      <th>Claimed</th>
      <th>Github profile</th>
      <th>Major</th>
      <th>Skills</th>
      <th>Github access token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

  <% @profiles.each do |profile| %>
    <tr>
      <td><%= profile.full_name %></td>
      <td>
      <% if profile.active %>
          <i class="icon-ok"></i>
      <% end %>
      </td>
      <td>
        <% if profile.profile_claim %>
          <span class="label label-warning">Pending</span>
        <% elsif profile.user %>
          <span class="label">Claimed</span>
        <% else %>
          <span class="label label-info">No User</span>
        <% end %>

      </td>
      <td><%= link_to_github profile.github_profile %></td>
      <td><%= profile.major %></td>
      <td>
        <% if profile.skill_tags.length %>
          <div class="btn-group">
            <a class="btn dropdown-toggle dropdown-hover" data-toggle="dropdown" href="#">
              <%= profile.skill_tags.first %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% profile.skill_tags.each do |skill| %>
                <li><a><%= skill %></a></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </td>
      <td><%= profile.github_access_token %></td>
      <td><%= link_to 'Show', profile %></td>
      <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
      <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </table>


  <%= link_to 'New Profile', new_profile_path, :class => "btn btn-mini btn-primary pull-right" %>
</div>

app/views/profiles/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>


<div class="span12">
  <div class="row">
    <div class="span1"><%= image_tag avatar_url(@profile), :class => "thumbnail" %></div>
    <div class="span11">
      <h3><%= @profile.full_name %></h3>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <dl class="dl-horizontal">
        <dt>Major</dt>
        <dd><%= @profile.major %></dd>
        
        <dt>Active</dt>
        <dd>
        <% if @profile.active %>
            <i class="icon-ok"></i>
        <% end %>
        </dd>
    
        <dt>Github</dt>
        <dd><%= link_to_github(@profile.github_profile) %></dd>
      </dl>
    </div>
    <div class="span6">
      <strong><p>Skills</p></strong>
      <% if @profile.skill_tags.length %>
        <% @profile.skill_tags.each do |skill| %>
          <span class="label label-info" style="line-height:25px"><%= skill %></span>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <h3>Projects</h3>
      
    </div>

  </div>


</div>



<% if @profile.profile_claim %>
  <p>
    Profile has a request out to be claimed by <%= @profile.profile_claim.email %> - <%= link_to 'Destroy', [@profile, @profile.profile_claim], confirm: 'Are you sure?', method: :delete %>
  </p>
<% end %>

<% if @profile.user %>
  <p>
    Profile has been claimed by <%= @profile.user.email %> - <%= link_to 'Destroy', @profile.user, confirm: 'Are you sure?', method: :delete %>
  </p>
<% end %>
<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>
<%= link_to 'Send Profile Claim', new_profile_profile_claim_path(@profile) unless @profile.profile_claim || @profile.user %>