config/routes.rb
TechClubWebsite::Application.routes.draw do

  get "front_page/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :comments
  
  resources :sessions 

  resources :profile_claims

  resources :profiles

  resources :users

  resources :posts

  resources :projects

  resources :profiles do
    resources :profile_claims, :path => "claim"
  end

  root :to => "front_page#index"

  match ":id" => "posts#show"

end

app/models/profile_claim.rb
# == Schema Information
#
# Table name: profile_claims
#
#  id         :integer          not null, primary key
#  email      :string(255)
#  profile_id :integer
#  token      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ProfileClaim < ActiveRecord::Base
  belongs_to :profile

  attr_accessible :email, :profile_id, :token
  
  def send_profile_claim
    generate_token(:token)
    save!
    UserMailer.profile_claim(self).deliver
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64

    end while ProfileClaim.exists?(column => self[column])

  end

end

app/controllers/profile_claims_controller.rb
class ProfileClaimsController < ApplicationController
  # GET /profile_claims
  # GET /profile_claims.json
  def index
    @profile_claims = ProfileClaim.find(:all, :include => [:profile])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profile_claims }
    end
  end

  # GET /profile_claims/1
  # GET /profile_claims/1.json
  def show
    @profile_claim = ProfileClaim.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profile_claim }
    end
  end

  # GET /profile_claims/new
  # GET /profile_claims/new.json
  def new
    @profile_claim = ProfileClaim.new({:profile_id => params[:profile_id]})

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profile_claim }
    end
  end

  # GET /profile_claims/1/edit
  def edit
    @profile_claim = ProfileClaim.find(params[:id])
  end

  # POST /profile_claims
  # POST /profile_claims.json
  def create
    @profile_claim = ProfileClaim.new(params[:profile_claim])

    respond_to do |format|
      if @profile_claim.save && @profile_claim.send_profile_claim
        format.html { redirect_to @profile_claim, notice: 'Profile claim was successfully created.' }
        format.json { render json: @profile_claim, status: :created, location: @profile_claim }
      else
        format.html { render action: "new" }
        format.json { render json: @profile_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profile_claims/1
  # PUT /profile_claims/1.json
  def update
    @profile_claim = ProfileClaim.find(params[:id])

    respond_to do |format|
      if @profile_claim.update_attributes(params[:profile_claim])
        format.html { redirect_to @profile_claim, notice: 'Profile claim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profile_claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profile_claims/1
  # DELETE /profile_claims/1.json
  def destroy
    @profile_claim = ProfileClaim.find(params[:id])
    @profile_claim.destroy

    respond_to do |format|
      format.html { redirect_to profile_claims_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profile_claims_helper.rb
module ProfileClaimsHelper
end

app/views/profile_claims/_form.html.erb
<%= form_for([@profile_claim.profile,@profile_claim]) do |f| %>
  <%= f.hidden_field :profile_id, :value => params[:profile_id] %>
  <% if @profile_claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile_claim.errors.count, "error") %> prohibited this profile_claim from being saved:</h2>

      <ul>
      <% @profile_claim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profile_claims/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @profile_claim %> |
<%= link_to 'Back', profile_claims_path %>

app/views/profile_claims/index.html.erb
<h3>Pending claims</h3>

<table class="table">
  <tr>
    <th>Email</th>
    <th>Profile</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profile_claims.each do |profile_claim| %>
  <tr>
    <td><%= profile_claim.email %></td>
    <td><%= link_to profile_claim.profile.full_name, profile_path(profile_claim.profile_id) %></td>
    <td><%= link_to 'Show', profile_claim %></td>
    <td><%= link_to 'Edit', edit_profile_claim_path(profile_claim) %></td>
    <td><%= link_to 'Destroy', profile_claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/profile_claims/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', profile_claims_path %>

app/views/profile_claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @profile_claim.email %>
</p>

<p>
  <b>Profile:</b>
  <%= @profile_claim.profile_id %>
</p>


<%= link_to 'Edit', edit_profile_claim_path(@profile_claim) %> |
<%= link_to 'Back', profile_claims_path %>