config/routes.rb
TechClubWebsite::Application.routes.draw do

  get "front_page/index"

  get "logout" => "sessions#destroy", :as => "logout"
  get "login"  => "sessions#new",     :as => "login"

  resources :comments
  
  resources :sessions 

  resources :profile_claims

  resources :profiles

  resources :users

  resources :posts

  resources :projects

  resources :profiles do
    resources :profile_claims, :path => "claim"
  end

  root :to => "front_page#index"

  match ":id" => "posts#show"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TechClubWebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    
    <div class="navbar navbar-fixed-bottom">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WSUTech</a>
          <div class="container nav-collapse">
            <ul class="nav">
	      <li><%= link_to_icon "Home", "icon-home icon-white", root_path %></li>
              <li><%= link_to_icon "Members", "icon-user icon-white", profiles_path %></li>
              <li><%= link_to_icon "Projects", "icon-folder-open icon-white", projects_path  %></li>
              <li><%= link_to_icon "Posts", "icon-file icon-white", posts_path  %></li>
              
            </ul>
            <% if current_user %>
            <div class="btn-group pull-right dropdown">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	        <i class="icon-cog"></i> <%= current_user.profile.full_name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu span2">
                <li><%= link_to_icon "Users", "icon-user", users_path  %></li>
                <li>
                <%= link_to profile_claims_path do %> 
                  <i class="icon-retweet"></i>
                  Profile Claims   
                  <span class="label label-info"><%= ProfileClaim.all.length %></span>
                
                <% end %>
                </li>
                <li class="divider"></li>
                <li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                <li class="divider"></li>
                <li><a href="<%= logout_path %>"><i class="icon-share"></i> Logout</a></li>
              </ul>
            </div>
            <% else %>
              <%= form_tag sessions_path, :class => "form-inline pull-right", :style => "margin-bottom:0px" do %>
                <%= text_field_tag :email, params[:email], :class => "input-small", :placeholder => "Email" %>
                <%= password_field_tag :password, nil, :class => "input-small", :placeholder => "Password" %>
                <!--<label class="checkbox">
                  <input type="checkbox"> Remember me
                </label>-->
                <button type="submit" class="btn">Sign in</button>
              <% end %>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container push20">
      <div class="page-header"> 
          <h1>WSU Tech Club <small>We build awesome shit</small></h1>
     </div> 
      <div class="content push50">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
            <div class="span3" style="display:none">
              <div class="well" style="padding: 8px 0">
                <ul class="nav nav-list">
                  <li class="nav-header">Recent Posts</li>
                  <li><%= link_to "Link1", "/path1"  %></li>
                  <li><%= link_to "Link2", "/path2"  %></li>
                  <li><%= link_to "Link3", "/path3"  %></li>
                </ul>
              </div><!--/.well -->
            </div><!--/span-->
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <small>&copy; WSUTech Club @ Washington State University 2012</small>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/frontpage.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "TechClubWebsite" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>
    
    <div class="navbar navbar-fixed-bottom">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">WSUTech</a>
          <div class="container nav-collapse">
            <ul class="nav">
	      <li><%= link_to_icon "Home", "icon-home icon-white", root_path %></li>
              <li><%= link_to_icon "Members", "icon-user icon-white", profiles_path %></li>
              <li><%= link_to_icon "Projects", "icon-folder-open icon-white", projects_path  %></li>
              <li><%= link_to_icon "Posts", "icon-file icon-white", posts_path  %></li>
              
            </ul>
            <% if current_user %>
            <div class="btn-group pull-right dropdown">
              <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
	        <i class="icon-cog"></i> <%= current_user.profile.full_name %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu span2">
                <li><%= link_to_icon "Users", "icon-user", users_path  %></li>
                <li>
                <%= link_to profile_claims_path do %> 
                  <i class="icon-retweet"></i>
                  Profile Claims   
                  <span class="label label-info"><%= ProfileClaim.all.length %></span>
                
                <% end %>
                </li>
                <li class="divider"></li>
                <li><a href="#"><i class="icon-wrench"></i> Settings</a></li>
                <li class="divider"></li>
                <li><a href="<%= logout_path %>"><i class="icon-share"></i> Logout</a></li>
              </ul>
            </div>
            <% else %>
              <%= form_tag sessions_path, :class => "form-inline pull-right", :style => "margin-bottom:0px" do %>
                <%= text_field_tag :email, params[:email], :class => "input-small", :placeholder => "Email" %>
                <%= password_field_tag :password, nil, :class => "input-small", :placeholder => "Password" %>
                <!--<label class="checkbox">
                  <input type="checkbox"> Remember me
                </label>-->
                <button type="submit" class="btn">Sign in</button>
              <% end %>
            <% end %>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

  <div class="wrapper">
		<div class="container">
			<header class="hero-unit">
				<h1>WSUTech Club</h1>
				<p>We are a group of computer enthusiasts, hackers and thinkers.</p>
			</header>
			<div class="row">
				<div class="span4">
					<h3>Howdy</h3>
					<p>Welcome to WSUTech, we are your average group of computer enthusiasts, hackers and thinkers.</p>
					<p>You can see some of the projects we are working on at our <a href="https://github.com/WSU-Tech-Club" target="_blank">github community</a>.
				</div>
				<div class="span4">
					<h3>Join Us</h3>
					<p>Come to our next meeting and introduce yourself! We are always looking for cool and interesting people to join the club.</p>
					<p>In the mean time, check out our <a href="https://www.facebook.com/groups/wsu.cpts.guild/383086725094690" target="_blank">facebook page</a>.</p>
				</div>
				<div class="span4">
					<h3>Talk to Us</h3>
					<p>Come hangout with us on IRC! There is always someone around, come in and say hello.</p>
					<p> #wsutech on freenode.net</p>
					<strong><a href="http://webchat.freenode.net?channels=#wsutech" target="_blank">Join now</a></strong>
				</div>
			</div>
			<hr>
			<div class="row">
				<div class="span7">
					<h2>Announcement</h2>
					<p class="alert"><strong>Next Meeting</strong> TBD</p>
					<p>We are currently working on a website, but in the mean time you can find all information about whats going on here.</p>
				</div>
				<div class="span5">
					<h3>Upcoming Events</h3>
					<table class="table table-striped">
						<thead>
							<tr>
								<th>Event</th>
								<th>Date &amp; Time</th>
								<th>Location</th>
							</tr>	
						</thead>
						<tbody>
							<tr>
								<td>LAN</td>
								<td>TBD</td>
								<td>TBD</td>
							</tr>
							<tr>
								<td><abbr title="Schweitzer Engineering Laboratories">SEL</abbr> Talk</td>
								<td>TBD</td>
								<td>TBD</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<div class="push"></div>
	</div>

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>